# Permalinks
permalink:           pretty

# Setup
title:               Jenn Wong
tagline:             Data Science & Machine Learning
url:                 http://cjenniferwong.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jenn Wong
  # url:
  # email:

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cjenniferwong

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - listen

# Page List
pages_list:
  About: '/about'
  Recent Posts: '/blogs.html'
  Projects: '/projects'
  Archive: '/archive'
  # Test: '/test.html'

# 2020-03-15 updates
plugins:
  - jekyll-gist
  - jekyll-paginate
